services:
  letsencrypt:
    container_name: "certbot-service"
    image: certbot/certbot:latest
    command: sh -c "certbot certonly --force-renewal --expand --webroot -w /tmp/acme_challenge -d www.digitaloctop.us -d digitaloctop.us --text --agree-tos --email kevin.haan@posteo.de --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges=http"
    entrypoint: ""
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/tmp/acme_challenge:/tmp/acme_challenge"
    environment:
      - TERM=xterm
