services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    command: nginx -g 'daemon off;'
    networks:
      - ${NETWORK_NAME}

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
    command: certonly --standalone --email kevin.haan@posteo.de --agree-tos --no-eff-email -d ${DROPLET_DOMAIN} -d www.${DROPLET_DOMAIN}
    # Füge weitere Optionen hinzu, falls benötigt

networks:
  ${NETWORK_NAME}:
    external: true
