services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-data:/data/letsencrypt
    command: certonly --standalone --email kevin.haan@posteo.de --agree-tos --no-eff-email -d ${DROPLET_DOMAIN} -d www.${DROPLET_DOMAIN}

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certs:/etc/letsencrypt
    networks:
      - network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot

networks:
  network:
    name: ${NETWORK_NAME}
    external: true
