version: "3.8"
services:
  api:
    build:
      context: ./api
      args:
        - PORT=${API_PORT}
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongo
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=${ENVIRONMENT}
      - MONGO_URI=${MONGO_URI}
    networks:
      - network

networks:
  network:
    name: ${NETWORK_NAME}
