name: Create MongoDB Container

on:
  workflow_dispatch: # Diese Aktion wird nur manuell ausgelöst

jobs:
  create-mongo-container:
    runs-on: ubuntu-latest

    steps:

    - name: Create and Start MongoDB Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        password: ${{ secrets.DROPLET_PASSWORD }}
        port: 22
        script: whoami
