name: Create MongoDB Container

on:
  workflow_dispatch: # Diese Aktion wird nur manuell ausgelöst

jobs:
  create-mongo-container:
    runs-on: ubuntu-latest

    steps:

    - name: Create and Start MongoDB Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.PRIVATE_SSH_KEY }}
        port: 22
        script: |
          echo "Container Name: ${{ env.MONGO_CONTAINER_NAME }}"
          echo "Network Name: ${{ env.NETWORK_NAME }}"
          echo "Mongo Port: ${{ env.MONGO_PORT }}"
          echo "Mongo Username: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}"
          echo "Mongo Password: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}"
