name: Deploy NGINX to Droplet

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/nginx.yml"
      - "nginx/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NGINX code
        uses: actions/checkout@v2

      - name: Transfer NGINX code to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          source: "nginx/*" # Überträgt nur die Inhalte des nginx-Ordners
          target: "." # Zielverzeichnis auf dem Droplet

      - name: SSH and Deploy NGINX to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            cd nginx
            export NETWORK_NAME=${{ vars.NETWORK_NAME }}
            export DROPLET_DOMAIN=${{ secrets.DROPLET_DOMAIN }}
            docker-compose up --build -d nginx
            docker-compose -f docker-compose-le.yml up --build
