name: Deploy NGINX to Droplet

on:
  workflow_dispatch:
  push:
    paths:
      - "nginx/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout NGINX code
        uses: actions/checkout@v2
        with:
          path: "nginx"

      - name: Transfer NGINX code to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          source: "nginx/*" # Überträgt nur die Inhalte des nginx-Ordners
          target: "/home/${{ secrets.DROPLET_USERNAME }}/nginx" # Zielverzeichnis auf dem Droplet

      - name: SSH and Deploy NGINX to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: |
            cd /home/${{ secrets.DROPLET_USERNAME }}/nginx
            sdocker network ls | grep ${{ vars.NETWORK_NAME }} || docker network create ${{ vars.NETWORK_NAME }}
            docker-compose up --build -d
